name: FastAPI CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:  # Continuous Integration (test + lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # kerakli versiyani kiriting

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

  cd:  # Continuous Deployment
    needs: ci  # Faqat CI muvaffaqiyatli bo‘lsa ishlaydi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI via SSH key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/api-orm-book
            git pull origin main
            # kerak bo‘lsa serverni restart qilish ham shu yerda bo‘lishi mumkin`